from typing import Literal

from pydantic import BaseModel, Field


ResponseActionType = Literal[
    "create_ticket",
    "notify",
    "block_ip",
    "manual_review",
]


class ToolRequest(BaseModel):
    """
    Dry-run tool request generated by Response Agent.

    This object describes an intended action only.
    It must not execute the action directly.
    """

    tool_name: ResponseActionType

    target: str | None = None

    reason: str

    parameters: dict = Field(
        default_factory=dict
    )


class ResponsePlan(BaseModel):
    """
    Structured response plan produced after
    grounded security analysis.
    """

    finding_id: int

    grounded_verdict: str

    decision_action: str

    priority: Literal[
        "low",
        "medium",
        "high",
    ]

    summary: str

    containment_plan: list[str] = Field(
        default_factory=list
    )

    remediation_plan: list[str] = Field(
        default_factory=list
    )

    verification_plan: list[str] = Field(
        default_factory=list
    )

    tool_requests: list[ToolRequest] = Field(
        default_factory=list
    )

    requires_human_review: bool

    dry_run: bool = True