from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
)


class StrictToolParameters(BaseModel):
    """
    Base contract for Tool Broker parameters.

    Unknown parameters are rejected so that
    LLM-generated tool input cannot silently
    introduce unsupported execution arguments.
    """

    model_config = ConfigDict(
        extra="forbid",
        strict=True,
    )


class CreateTicketParameters(
    StrictToolParameters
):
    """
    Current create_ticket executor operates from
    ToolRequest.target.

    No additional parameters are currently supported.
    """

    pass


class NotifyParameters(
    StrictToolParameters
):
    """
    Current notify executor operates from
    ToolRequest.target.

    No additional parameters are currently supported.
    """

    pass


class BlockIpParameters(
    StrictToolParameters
):
    """
    Current block_ip executor operates from
    ToolRequest.target.

    No additional parameters are currently supported.
    """

    pass


class ManualReviewParameters(
    StrictToolParameters
):
    """
    Structured parameters generated by the
    deterministic manual-review safety guardrail.
    """

    finding_id: int = Field(
        ge=1,
    )

    grounded_verdict: str = Field(
        min_length=1,
        max_length=100,
    )